// <auto-generated />
using HeatPumpCalculator.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeatPumpCalculator.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260718132133_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("HeatPumpCalculator.Api.Models.BillingPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("HeatPumpMeterReading")
                        .HasColumnType("REAL");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("SarahSharePercent")
                        .HasColumnType("REAL");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalConsumptionKwh")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("BillingPeriods");
                });

            modelBuilder.Entity("HeatPumpCalculator.Api.Models.MonthlyBill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BillingPeriodId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Consumption")
                        .HasColumnType("REAL");

                    b.Property<double>("Cost")
                        .HasColumnType("REAL");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BillingPeriodId");

                    b.ToTable("MonthlyBills");
                });

            modelBuilder.Entity("HeatPumpCalculator.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HeatPumpCalculator.Api.Models.WaterPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("DavidColdReading")
                        .HasColumnType("REAL");

                    b.Property<double?>("DavidWarmReading")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsBaseline")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("SarahColdReading")
                        .HasColumnType("REAL");

                    b.Property<double?>("SarahWarmReading")
                        .HasColumnType("REAL");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("TotalMeterReading")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("WaterPeriods");
                });

            modelBuilder.Entity("HeatPumpCalculator.Api.Models.MonthlyBill", b =>
                {
                    b.HasOne("HeatPumpCalculator.Api.Models.BillingPeriod", "BillingPeriod")
                        .WithMany("MonthlyBills")
                        .HasForeignKey("BillingPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BillingPeriod");
                });

            modelBuilder.Entity("HeatPumpCalculator.Api.Models.BillingPeriod", b =>
                {
                    b.Navigation("MonthlyBills");
                });
#pragma warning restore 612, 618
        }
    }
}
